/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Docusaurus OpenAPI",
  "tagline": "OpenAPI plugin for generating API reference docs in Docusaurus v2.",
  "url": "https://docusaurus-openapi.netlify.app",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "cloud-annotations",
  "projectName": "docusaurus-openapi",
  "presets": [
    [
      "docusaurus-preset-openapi",
      {
        "api": {
          "path": "examples/petstore.yaml",
          "routeBasePath": "petstore"
        },
        "docs": {
          "sidebarPath": "/Users/benzsupaluk/Vistec/clone/demo/sidebars.js",
          "editUrl": "https://github.com/cloud-annotations/docusaurus-openapi/edit/main/demo/"
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/benzsupaluk/Vistec/clone/demo/src/css/custom.css"
        },
        "proxy": {
          "/proxy": {
            "target": "http://localhost:8091",
            "pathRewrite": {
              "^/proxy": ""
            }
          }
        }
      }
    ]
  ],
  "plugins": [
    [
      "docusaurus-plugin-openapi",
      {
        "id": "cos",
        "path": "examples/openapi-cos.json",
        "routeBasePath": "cos"
      }
    ],
    [
      "docusaurus-plugin-openapi",
      {
        "id": "multi-spec",
        "path": "examples",
        "routeBasePath": "multi-spec"
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "dark",
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "OpenAPI",
      "logo": {
        "alt": "Docusaurus Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro",
          "position": "left",
          "label": "Docs"
        },
        {
          "label": "Examples",
          "position": "left",
          "items": [
            {
              "to": "/petstore",
              "label": "Petstore"
            },
            {
              "to": "/cos",
              "label": "Cloud Object Storage"
            },
            {
              "to": "/multi-spec",
              "label": "Multi-spec"
            }
          ]
        },
        {
          "href": "https://github.com/cloud-annotations/docusaurus-openapi",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Deploys by Netlify",
        "src": "https://www.netlify.com/img/global/badges/netlify-color-accent.svg",
        "width": 160,
        "height": 51,
        "href": "https://www.netlify.com"
      },
      "copyright": "Copyright © 2022 Cloud Annotations. Built with Docusaurus.",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "api": {
      "authPersistance": "localStorage"
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
